Client pool improvements
wtsi-npg/extendo pull request #19
Opened 2020-02-03 09:33 UTC by kjsanger

Adds client-checking to the pool that stops and removes idle and long-running clients.

Refactors the pool from using channels to a mutex in order to achieve this.

Changes the signature of `NewClientPool` to allow the various timeouts to be set, hence requires a major version bump.

2020-02-11 15:12 UTC, sb10 requested changes
Lack of mutex locks need fixing. Maybe come up with some tests first that trigger the race detector (and run your automated tests with the race detector on).

2020-02-11 15:12 UTC, sb10 commented on client.go
> +	go func(c *Client) {
Why pass in client but nothing else? Likewise with other go funcs in this method, there's no loop here so no closure-related variable bugs to worry about. Or to pre-emptively defend against them, pass in all used variables?

2020-02-11 15:12 UTC, sb10 commented on client.go
> +	client.pid = pid
Rather than the big block of assignments afterwards, why not assign values directly to `client.` when they are made?

2020-02-11 15:12 UTC, sb10 commented on client.go
> +	client.startTime = time.Now()
Setting isRunning and startTime after the code that sets stopTime is not clear in terms of reading flow.

2020-02-11 15:12 UTC, sb10 commented on client.go
>  		perr := cmd.Wait()
Earlier you declared perr as an error channel. Now you use the same variable name to hold an error that you feed in to a (different) error channel. I'm confused if any of this is necessary.

2020-02-11 15:12 UTC, sb10 commented on client.go
> +		close(c.err)
I think client.err only ever receives this 1 error and is closed? So I think client.err should actually just be of type error and (under mutex protection) you just need to `c.err = perr`

2020-02-11 15:12 UTC, sb10 commented on client.go
> +	if client.isRunning {
This lacks necessary mutex protection. You could make the mutex an RW and do a read lock here.

2020-02-11 15:12 UTC, sb10 commented on client.go
> +	if !client.isRunning {
This lacks necessary mutex protection.

2020-02-11 15:12 UTC, sb10 commented on client_pool.go
> +	pool.Lock()
Could make the mutex RW and have an `RLock` here.

2020-02-11 15:12 UTC, sb10 commented on client_pool.go
> +				pool.numClients = pool.numClients - numRemoved
I found the idea of numClients vs clients surprising. It feels fragile that the pool's knowledge of how many clients there are depends on user behaviour (what happens if they `Return()` a non-running client that wasn't made by this pool?...).
I'd prefer that `Get()` clients are stored in the pool before returning them, and `len(pool.clients)` be the canonical and checked value for number of clients. Non-running ones can be popped off as done in this method. The difference between clients that are in user hands vs ones that have been returned could be a client flag?
Maybe it's not worth making such a change, or it doesn't make sense, but numClients getting out of sync with reality does seem like a possible bug in the future.

2020-02-11 16:12 UTC, kjsanger commented on client.go
> +	client.startTime = time.Now()
Swapped.

2020-02-11 16:13 UTC, kjsanger commented on client.go
> +	go func(c *Client) {
That's an artefact from an abandoned change I included by mistake. I'll revert these lines.

2020-02-11 16:34 UTC, kjsanger commented on client.go
> +	client.pid = pid
It's so that one can create a non-running client with the constructor and then start it when needed and allows an intuitive `Start` and `Stop` API. Most of those fields have no valid value until the client is started.

2020-02-12 08:32 UTC, sb10 commented on client.go
> +	client.pid = pid
I meant within this `Start` method. eg. on line 280, instead of `pid := cmd.Process.Pid` you'd do `client.pid = cmd.Process.Pid`

2020-02-12 11:19 UTC, kjsanger commented on client.go
> +	client.pid = pid
Okay, I understand. I wrote it like that so that in the body of the function a lot of the code is shortened e.g. `stdin` versus `client.stdin`, which makes it less noisy. In fact, I would like to pull out `client.path` as a shorter named local variable because of the number of times it appears in the logging code. I think it's a matter of taste.

2020-02-12 11:27 UTC, kjsanger commented on client.go
>  		perr := cmd.Wait()
Reuse of the variable name is a mistake - changed now. There's one error channel `client.err`, hopefully the update clarifies that.

2020-02-12 11:28 UTC, kjsanger commented on client.go
> +		close(c.err)
Thanks, I can look at that as a future change. I'd rather not expand the scope of this one, though.

2020-02-12 11:29 UTC, kjsanger commented on client.go
> +	if client.isRunning {
Fixed.

2020-02-12 11:42 UTC, kjsanger commented on client.go
> +	if !client.isRunning {
I can't lock here as the `execute` may call itself recursively (via `listRecurse`). Instead, I've added locks to the individual exported methods that call `execute`

2020-02-12 11:58 UTC, kjsanger commented on client_pool.go
> +	pool.Lock()
Done.

2020-02-12 12:18 UTC, kjsanger commented on client_pool.go
> +				pool.numClients = pool.numClients - numRemoved
I'd rather revisit the design as an enhancement in a separate pull request. There are indeed downsides to a simple counter of clients.

2020-02-12 13:38 UTC, sb10 commented on client.go
> +	client.pid = pid
Yes, it may be a matter of taste. But I think it's extra lines of code that can lead to bugs. What if future you/other developer takes one of these pulled out variables, modifies it, but then forgets to set it back on client? What if the `client.xyz` variable is modified, then the `xyz` variable is modified, and set on client, replacing the value in an unintended way?
I think sometimes it makes sense to pull it out, and I frequently do it myself, but not on a systematic basis to avoid repeating `client.` a few times.

2020-02-12 13:53 UTC, sb10 reviewed
Double-check there's not a better way to handle locking for execute.

2020-02-12 13:53 UTC, sb10 commented on client.go
> +	if !client.isRunning {
Not sure I follow. `listRecurse` calls `execute`, and recurses on itself, but execute doesn't call itself, so you're safe?
If you're really not able to do that, then I'd suggest adding a comment to `execute` that states that you must hold the lock before calling execute.
Even with that in place, I have done this sort of thing many times, and it's always a mistake. You always end up with deadlock bugs in the future because you forget to get the lock before calling the method. It's well worth rearchitecting things to have the lock within the method, self contained.

2020-02-12 13:56 UTC, sb10 commented on client.go
> +	go func(c *Client) {
You still pass in `cancelCtx` to the other go funcs. Not sure if there's a reason for that?

2020-02-12 14:27 UTC, kjsanger commented on client.go
> +	if !client.isRunning {
You're right ... the `execute` releases the lock before the recursion.

2020-02-12 14:27 UTC, kjsanger commented on client.go
> +	client.pid = pid
I made the change to see what it's like (adding `client.` 24 times in this case). I find it harder to read and the state changes to the client are now scattered throughout the method, rather than all togther. I'm going to leave this as is.

2020-02-12 14:53 UTC, kjsanger commented on client.go
> +	go func(c *Client) {
Originally it was to emphasise the "cancellable" aspect of these functions when someone came to maintain the code.

2020-02-12 15:39 UTC, sb10 approved these changes

2020-02-12 21:56 UTC, merged